#!/bin/bash

function status {
    pid=$(pgrep -x redshift)
    if [ $pid -gt 0 ]
    then
	echo '<span foreground="#00FF40"><b>Redshift</b></span>'
    else
	echo '<span foreground="red"><b>Redshift</b></span>'
    fi
}

function toggle_redshift {
    pid=$(pgrep -x redshift)
    if [ $pid -gt 0 ]
    then
	systemctl --user stop redshift.service
    else
	systemctl --user start redshift.service
    fi
}

case $BLOCK_BUTTON in
  1) toggle_redshift;;
esac

status
